// src/game/components/game.status.tsx
import { useGameContext } from '../game.hooks'
import { eGameState } from '../game.enums'

export default function GameStatus() {
    const { state } = useGameContext()

    let statusText: string
    let statusBackgroundColor: string
    if (state.isVictory) {
        statusText = eGameState.VICTORY
        statusBackgroundColor = (state.step % 2) === 0
            ? 'victory-x'
            : 'victory-o'
    }
    else if (state.isDraw) {
        statusText = eGameState.DRAW
        statusBackgroundColor = 'draw'
    }
    else {
        statusText = eGameState.PLAYING
        statusBackgroundColor = 'playing'
    }

    return (
        <div>
            <div className={`status ${statusBackgroundColor}`}>
                Status : <span>{statusText}</span>
            </div>
        </div>
    )
}

// src/game/components/game.status.vue
<script setup lang="ts">
import { eGameState } from '../game.enums'
import store from '../store'

let statusText: string
if (store.state.isVictory)
  statusText = eGameState.VICTORY
else if (store.state.isDraw)
  statusText = eGameState.DRAW
else
  statusText = eGameState.PLAYING
</script>

<template>
  <div>
    <div
      class="status"
      :class="{
        'playing': !store.state.isVictory && !store.state.isDraw,
        'victory-x': store.state.isVictory && store.xIsNext,
        'victory-o': store.state.isVictory && !store.xIsNext,
        'draw': store.state.isDraw,
      }"
    >
      Status : <span>{{ statusText }}</span>
    </div>
  </div>
</template>
